
app.datasource.node1.jdbc-url=jdbc:mysql://localhost:3306/db_node1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.datasource.node1.username=root
app.datasource.node1.password=123456
app.datasource.node1.driver-class-name=com.mysql.cj.jdbc.Driver

app.datasource.node2.jdbc-url=jdbc:mysql://localhost:3306/db_node2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.datasource.node2.username=root
app.datasource.node2.password=123456
app.datasource.node2.driver-class-name=com.mysql.cj.jdbc.Driver

app.datasource.node3.jdbc-url=jdbc:mysql://localhost:3306/db_node3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.datasource.node3.username=root
app.datasource.node3.password=123456
app.datasource.node3.driver-class-name=com.mysql.cj.jdbc.Driver

# Quorum read (R): FULL N=3 -> R=2; PARTIAL N=2 -> R=2
replication.quorum.read.full=2
replication.quorum.read.partial=2
